src/Entity/CountableEntityInterface.php
<?php
declare(strict_types=1);

namespace App\Entity;

interface CountableEntityInterface
{
    public function getQuantity(): int;
}

templates/pdf/components/article_table.html.twig
<table class="table">
    <caption class="mt-4 bg-light p-2">
        <span class="fw-bold">{{ tax }}%</span>
        {{ 'SalesTax' | trans }}
    </caption>
    <thead>
    <tr>
        <th>{{ 'Product Name' | trans }}</th>
        <th>{{ 'Quantity' | trans }}</th>
        <th>{{ 'Price Sum' | trans }}</th>
    </tr>
    </thead>
    <tbody>
    {% for article in articles %}
        {# @var article \App\Model\ReceiptArticle #}
        <tr>
            <th>{{ article.name }}</th>
            <td>{{ article.quantity }}</td>
            <td>{{ article.price | string | format_currency('EUR') }}</td>
        </tr>
    {% endfor %}
    </tbody>
    <tfoot>
    {% for type, price in paymentPrices | filter((price) => price != 0.0) %}
        {# @var price \BcMath\Number #}
        <tr>
            <td></td>
            <td class="text-end">{{ type | trans(domain: 'receipt') }}:</td>
            <td>{{ price | string | format_currency('EUR') }}</td>
        </tr>
    {% endfor %}
    </tfoot>
    <tfoot>
    <tr>
        <td colspan="2"></td>
        <th class="text-decoration-double">
            {{ articles
            | reduce((carry, article) => carry + article.price, 0.0)
            | string
            | format_currency('EUR') }}
        </th>
    </tr>
    </tfoot>
</table>

templates/pdf/components/article_tax_sum_table.html.twig
{# @var array<int, array<string, \BcMath\Number>> paymentPrices #}
<table class="table mt-4">
    <thead>
    <tr>
        <th colspan="2" class="text-center">{{ 'Sum'|trans }}</th>
    </tr>
    </thead>
    <tfoot>
    {% set sums = {} %}
    {% for prices in paymentPrices %}
        {% for type, price in prices %}
            {# @var price \BcMath\Number #}
            {% set sums = sums | merge({(type): (sums[type] ?? 0.0) + price}) %}
        {% endfor %}
    {% endfor %}

    {% for type, price in sums | filter((price) => price > 0.0) %}
        <tr>
            <td class="text-end">{{ type | trans(domain: 'receipt') }}:</td>
            <td>{{ price | string | format_currency('EUR') }}</td>
        </tr>
    {% endfor %}
    </tfoot>
    <tfoot>
    <tr>
        <td></td>
        <th class="text-decoration-double">
            {{ sums
            | reduce((carry, sum) => carry + sum, 0.0)
            | string
            | format_currency('EUR') }}
        </th>
    </tr>
    </tfoot>
</table>